export const demoTeammates = [
  {
    id: "demo-t1",
    email: "sarah.chen@mergex.in",
    firstName: "Sarah",
    lastName: "Chen",
    designation: "CX Director",
    status: "ACTIVE" as const,
    role: { label: "CX Executive" },
  },
  {
    id: "demo-t2",
    email: "marcus.vance@mergex.in",
    firstName: "Marcus",
    lastName: "Vance",
    designation: "CX Executive",
    status: "ACTIVE" as const,
    role: { label: "CX Executive" },
  },
  {
    id: "demo-t3",
    email: "john.carter@mergex.in",
    firstName: "John",
    lastName: "Carter",
    designation: "CX Executive",
    status: "ACTIVE" as const,
    role: { label: "CX Executive" },
  },
];

export const demoClients = [
  {
    id: "demo-c1",
    companyName: "Stark Industries",
    contactPerson: "Pepper Potts",
    status: "active",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-c2",
    companyName: "Wayne Enterprises",
    contactPerson: "Lucius Fox",
    status: "active",
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-c3",
    companyName: "Oscorp Technologies",
    contactPerson: "Norman Osborn",
    status: "active",
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-c4",
    companyName: "Pym Particles",
    contactPerson: "Hope van Dyne",
    status: "active",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoProposals = [
  {
    id: "demo-p1",
    title: "Arc Reactor CX Implementation Plan",
    proposalNumber: "PRP-2026-0045",
    status: "ACCEPTED",
    value: 120000,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-p2",
    title: "Satellite Uplink Handoff & Training SLA",
    proposalNumber: "PRP-2026-0046",
    status: "SENT",
    value: 75000,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-p3",
    title: "Cross-Division CRM Alignment Audit",
    proposalNumber: "PRP-2026-0047",
    status: "DRAFT",
    value: 45000,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-p4",
    title: "Sub-atomic Quantum Portal SLA",
    proposalNumber: "PRP-2026-0048",
    status: "SENT",
    value: 185000,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const demoLeads = [
  {
    id: "demo-l1",
    companyName: "Stark Industries",
    contactPerson: "Pepper Potts",
    email: "pepper@stark.com",
    phone: "+1-555-0199",
    expectedValue: 120000,
    winLossStatus: "WON",
    nextActionDate: null,
    createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t1",
      firstName: "Sarah",
      lastName: "Chen",
      email: "sarah.chen@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "won-stage",
      name: "won",
      label: "Closed Won",
      color: "#10B981",
    },
    source: {
      id: "src-inbound",
      name: "Inbound Request",
    },
  },
  {
    id: "demo-l2",
    companyName: "Wayne Enterprises",
    contactPerson: "Lucius Fox",
    email: "l.fox@waynecorp.com",
    phone: "+1-555-0188",
    expectedValue: 75000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // Overdue
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t2",
      firstName: "Marcus",
      lastName: "Vance",
      email: "marcus.vance@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-neg",
      name: "negotiation",
      label: "Negotiation",
      color: "#F59E0B",
    },
    source: {
      id: "src-linkedin",
      name: "LinkedIn Outreach",
    },
  },
  {
    id: "demo-l3",
    companyName: "Oscorp Technologies",
    contactPerson: "Norman Osborn",
    email: "nosborn@oscorp.com",
    phone: "+1-555-0177",
    expectedValue: 95000,
    winLossStatus: "LOST",
    nextActionDate: null,
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t3",
      firstName: "John",
      lastName: "Carter",
      email: "john.carter@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "lost-stage",
      name: "lost",
      label: "Closed Lost",
      color: "#EF4444",
    },
    source: {
      id: "src-cold-email",
      name: "Cold Email Campaign",
    },
  },
  {
    id: "demo-l4",
    companyName: "Pym Particles",
    contactPerson: "Hope van Dyne",
    email: "hope@pym.com",
    phone: "+1-555-0166",
    expectedValue: 185000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t1",
      firstName: "Sarah",
      lastName: "Chen",
      email: "sarah.chen@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-prop",
      name: "proposal",
      label: "Proposal Sent",
      color: "#3B82F6",
    },
    source: {
      id: "src-referral",
      name: "Partner Referral",
    },
  },
  {
    id: "demo-l5",
    companyName: "S.H.I.E.L.D. Division",
    contactPerson: "Nick Fury",
    email: "fury@shield.gov",
    phone: "+1-555-0155",
    expectedValue: 500000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t2",
      firstName: "Marcus",
      lastName: "Vance",
      email: "marcus.vance@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-demo",
      name: "demo",
      label: "Product Demo",
      color: "#8B5CF6",
    },
    source: {
      id: "src-referral",
      name: "Partner Referral",
    },
  },
  {
    id: "demo-l6",
    companyName: "LexCorp",
    contactPerson: "Mercy Graves",
    email: "mgraves@lexcorp.com",
    phone: "+1-555-0144",
    expectedValue: 140000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // Overdue
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t3",
      firstName: "John",
      lastName: "Carter",
      email: "john.carter@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-disc",
      name: "discovery",
      label: "Discovery Call",
      color: "#EC4899",
    },
    source: {
      id: "src-linkedin",
      name: "LinkedIn Outreach",
    },
  },
  {
    id: "demo-l7",
    companyName: "Star Labs",
    contactPerson: "Cisco Ramon",
    email: "cisco@starlabs.com",
    phone: "+1-555-0133",
    expectedValue: 45000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t1",
      firstName: "Sarah",
      lastName: "Chen",
      email: "sarah.chen@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-intake",
      name: "intake",
      label: "Lead Intake",
      color: "#94A3B8",
    },
    source: {
      id: "src-referral",
      name: "Partner Referral",
    },
  },
  {
    id: "demo-l8",
    companyName: "Queen Industries",
    contactPerson: "Oliver Queen",
    email: "oliver@queen.com",
    phone: "+1-555-0122",
    expectedValue: 85000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t2",
      firstName: "Marcus",
      lastName: "Vance",
      email: "marcus.vance@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-review",
      name: "review",
      label: "Business Review",
      color: "#38BDF8",
    },
    source: {
      id: "src-cold-email",
      name: "Cold Email Campaign",
    },
  },
  {
    id: "demo-l9",
    companyName: "Kord Industries",
    contactPerson: "Ted Kord",
    email: "ted@kord.com",
    phone: "+1-555-0111",
    expectedValue: 60000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t3",
      firstName: "John",
      lastName: "Carter",
      email: "john.carter@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-qual",
      name: "qualification",
      label: "Qualification",
      color: "#60A5FA",
    },
    source: {
      id: "src-linkedin",
      name: "LinkedIn Outreach",
    },
  },
  {
    id: "demo-l10",
    companyName: "Tyrell Corporation",
    contactPerson: "Eldon Tyrell",
    email: "tyrell@tyrell.com",
    phone: "+1-555-0100",
    expectedValue: 300000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t1",
      firstName: "Sarah",
      lastName: "Chen",
      email: "sarah.chen@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-hot",
      name: "hot",
      label: "Hot Leads",
      color: "#F43F5E",
    },
    source: {
      id: "src-inbound",
      name: "Inbound Request",
    },
  },
  {
    id: "demo-l11",
    companyName: "Cyberdyne Systems",
    contactPerson: "Miles Dyson",
    email: "dyson@cyberdyne.com",
    phone: "+1-555-0112",
    expectedValue: 150000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t2",
      firstName: "Marcus",
      lastName: "Vance",
      email: "marcus.vance@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-qual-2",
      name: "qualification",
      label: "Qualification",
      color: "#60A5FA",
    },
    source: {
      id: "src-inbound",
      name: "Inbound Request",
    },
  },
  {
    id: "demo-l12",
    companyName: "Umbrella Corporation",
    contactPerson: "Albert Wesker",
    email: "wesker@umbrella.com",
    phone: "+1-555-0123",
    expectedValue: 220000,
    winLossStatus: "OPEN",
    nextActionDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    owner: {
      id: "demo-t3",
      firstName: "John",
      lastName: "Carter",
      email: "john.carter@mergex.in",
      avatarUrl: null,
    },
    stage: {
      id: "stage-review-2",
      name: "review",
      label: "Business Review",
      color: "#38BDF8",
    },
    source: {
      id: "src-linkedin",
      name: "LinkedIn Outreach",
    },
  },
];

export const demoMeetings = [
  {
    id: "demo-m1",
    title: "Discovery: Stark Industries Portal",
    scheduledAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // Past
    duration: 30,
    mode: "GOOGLE_MEET",
    meetingUrl: "https://meet.google.com/abc-defg-hij",
    status: "COMPLETED",
    lead: {
      id: "demo-l1",
      companyName: "Stark Industries",
      contactPerson: "Pepper Potts",
    },
    organizer: {
      firstName: "Sarah",
      lastName: "Chen",
      avatarUrl: null,
    },
  },
  {
    id: "demo-m2",
    title: "Negotiation Alignment: Wayne Enterprises",
    scheduledAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // Tomorrow
    duration: 45,
    mode: "ZOOM",
    meetingUrl: "https://zoom.us/j/123456789",
    status: "SCHEDULED",
    lead: {
      id: "demo-l2",
      companyName: "Wayne Enterprises",
      contactPerson: "Lucius Fox",
    },
    organizer: {
      firstName: "Marcus",
      lastName: "Vance",
      avatarUrl: null,
    },
  },
  {
    id: "demo-m3",
    title: "SLA Handoff: Pym Particles",
    scheduledAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // Future
    duration: 60,
    mode: "MICROSOFT_TEAMS",
    meetingUrl: "https://teams.microsoft.com/l/meetup-join",
    status: "SCHEDULED",
    lead: {
      id: "demo-l4",
      companyName: "Pym Particles",
      contactPerson: "Hope van Dyne",
    },
    organizer: {
      firstName: "Sarah",
      lastName: "Chen",
      avatarUrl: null,
    },
  },
  {
    id: "demo-m4",
    title: "High-Priority Strategy: S.H.I.E.L.D.",
    scheduledAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(), // Future
    duration: 60,
    mode: "GOOGLE_MEET",
    meetingUrl: "https://meet.google.com/xyz-qprs-tuv",
    status: "SCHEDULED",
    lead: {
      id: "demo-l5",
      companyName: "S.H.I.E.L.D. Division",
      contactPerson: "Nick Fury",
    },
    organizer: {
      firstName: "Marcus",
      lastName: "Vance",
      avatarUrl: null,
    },
  },
];

export const demoActions = [
  {
    id: "demo-a1",
    text: "Approve Arc Reactor SLA contract for Stark Industries",
    urgency: "High",
    done: false,
  },
  {
    id: "demo-a2",
    text: "Follow up on Wayne Enterprises contract negotiation timeline",
    urgency: "High",
    done: false,
  },
  {
    id: "demo-a3",
    text: "Prepare technical architecture specs for S.H.I.E.L.D.",
    urgency: "Medium",
    done: false,
  },
  {
    id: "demo-a4",
    text: "Assign onboarding coordinator for Pym Particles account",
    urgency: "Low",
    done: false,
  },
];

export const demoActivities = [
  {
    id: "act-1",
    type: "lead" as const,
    user: "Sarah Chen",
    avatarInitials: "SC",
    action: "marked lead as WON",
    target: "Stark Industries",
    time: "2 hours ago",
    color: "text-emerald-500 bg-emerald-500/10 border-emerald-500/20",
  },
  {
    id: "act-2",
    type: "proposal" as const,
    user: "Marcus Vance",
    avatarInitials: "MV",
    action: "sent technical proposal to",
    target: "Wayne Enterprises",
    time: "4 hours ago",
    color: "text-[#8B5CF6] bg-[#8B5CF6]/10 border-[#8B5CF6]/20",
  },
  {
    id: "act-3",
    type: "meeting" as const,
    user: "John Carter",
    avatarInitials: "JC",
    action: "completed Discovery Meeting with",
    target: "LexCorp",
    time: "Yesterday",
    color: "text-blue-500 bg-blue-500/10 border-blue-500/20",
  },
  {
    id: "act-4",
    type: "client" as const,
    user: "Sarah Chen",
    avatarInitials: "SC",
    action: "completed onboarding setup for",
    target: "Oscorp Technologies",
    time: "2 days ago",
    color: "text-pink-500 bg-pink-500/10 border-pink-500/20",
  },
  {
    id: "act-5",
    type: "lead" as const,
    user: "System",
    avatarInitials: "SYS",
    action: "qualified inbound lead from",
    target: "Pym Particles (ICP Score: 92)",
    time: "3 days ago",
    color: "text-amber-500 bg-amber-500/10 border-amber-500/20",
  },
];
